Repository amondnet/vercel-action, pull requests merged in 2020-12, with the labels that each got.

#59 ci: pull_request_target
  .github/workflows/deploy.yml
  .github/workflows/example-angular.yml
  .github/workflows/example-express-basic-auth.yml
  .github/workflows/example-scope.yml
  .github/workflows/example-static.yml
  .github/workflows/test.yml
Labels: Type: CI

#56 feat: enable users to customize github comment
  README.md
  dist/index.js
  index.js
  package-lock.json
Labels: Priority: Medium, Type: Feature

#63 ci: use pull request target
  .github/workflows/example-angular.yml
  .github/workflows/example-express-basic-auth.yml
  .github/workflows/example-scope.yml
  .github/workflows/example-static.yml
Labels: Type: CI

#62 docs: remove deprecated package now/node-server
  README.md
  example/express-basic-auth/now.json
Labels: Priority: Medium, Type: Documentation
